spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:D:/Zaj\u0119cia/IT/Java/udemy/todo-app/todo-db'
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baselineOnMigrate: false
management:
 endpoints:
   web:
     exposure:
       include: '*'
keycloak:
  auth-server-url: 'http://localhost:8180/auth'
  realm: 'TodoApp'
  resource: 'todo-spring-client'
  public-client: true